#!/bin/sh
#
# libprof -- run a program with libprof.so.1
#
ProgName=`basename $0`
#LIBPROF=/usr/lib/libprof_libc.so.1
#LIBPROF=./libprof_libc.so.1
LIBPROF=$HOME/lib/libprof_libc.so.1


main() {
	name=$1

	if [ $# -lt 1 ]; then
		say "$ProgName error: you must supply a program-name"
		say "Usage: $0 program [parameters]"
		exit 1
	fi
	LD_PRELOAD=$LIBPROF "$@"
}

say() {
	echo "$@" 1>&2
}

main "$@"
